function AfficheCurseur(i)
Liste_Fichier=getappdata(gcbf,'liste_fichier');
    line([Liste_Fichier(1,1).Tab_Temps{1}(i) Liste_Fichier(1,1).Tab_Temps{1}(i)],...
        get(findobj('tag','graph2D_1'),'YLim'),...
        'color','r',...
        'parent',findobj('tag','graph2D_1'),...
        'tag','anim',...
        'linewidth',1);
    
    line([Liste_Fichier(1,1).Tab_Temps{1}(i) Liste_Fichier(1,1).Tab_Temps{1}(i)],...
        get(findobj('tag','graph2D_2'),'Ylim'),...
        'color','r',...
        'parent',findobj('tag','graph2D_2'),...
        'tag','anim',...
        'linewidth',1);
    
    line([Liste_Fichier(1,1).Tab_Temps{1}(i) Liste_Fichier(1,1).Tab_Temps{1}(i)],...
        get(findobj('tag','graph2D_3'),'Ylim'),...
        'color','r',...
        'parent',findobj('tag','graph2D_3'),...
        'tag','anim',...
        'linewidth',1);
end

