function InterfaceGraphiqueJambes
close all;
clear;
clc
cd('fonction')
FlagStop=true;
FlagLecture=true;
Tab_Temps{1}(1)=0;
VitesseLecture=1;
ZoomStatut = false;
Nb_Fichier_Charger = 0;
Liste_Marqueur = struct ('Nom_Marqueur',...
    'X',...
    'Y',...
    'Z',...
    'Visible',{'on','off'});
Liste_Fichier = struct ('Nom_Fichier','Inconnue',...
    'Tab_Temps',Tab_Temps,...
    'Liste_Marqueur',Liste_Marqueur,...
    'Menu_Affiche_Mq','vide');


%Creation fenêtre principale
FenetrePrincipale = figure('Units','normalized',...
    'Position',[0.01 0.1 0.9 0.8],...
    'name','Interface Outils analyse du mouvement (Jambe)',...
    'doublebuffer','on');

%Creation des options sur la barre de menu
Menu_Mq = uimenu('label','Liste Marqueur',...
    'parent',FenetrePrincipale);
Menu_Statistique = uimenu('label','Statistique',...
    'parent',FenetrePrincipale);
Menu_AfficheStatistique = uimenu(Menu_Statistique,...
    'label','Affiche Statistique',...
    'callback',@AfficheStatistique);
Menu_EnregistrerStatistique = uimenu(Menu_Statistique,...
    'label','Enregistrer Statistique',...
    'callback',@EnregistrerStatistique);

%Creation des panels
Panel3D = uipanel('BorderType','etchedin',...
    'Position',[0.01 0.05 0.5 0.9],...
    'Parent',FenetrePrincipale,...
    'Title','Graphique 3D');
Panel2D = uipanel('BorderType','etchedin',...
    'Position',[0.52 0.05 0.35 0.9],...
    'Parent',FenetrePrincipale,...
    'Title','Graphique 2D');
PanelMenu = uipanel('Bordertype','etchedin',...
    'Position',[0.88 0.5 0.11 0.45],...
    'Parent',FenetrePrincipale,...
    'Title','Menu');

%Creation des axes
Hgraph3D=axes('units','normalized',...
    'ActivePositionProperty','position',...
    'position',[0.1 0.1 0.8 0.8],...
    'Parent',Panel3D,...
    'tag','graph3D');
axis(Hgraph3D,[-4000 4000 -1000 500 -100 2000],'equal');
Hgraph2D_1 = axes('Units','normalized',...
    'ActivePositionProperty','position',...
    'position',[0.1 0.69 0.85 0.23],...
    'Parent',Panel2D,...
    'tag','graph2D_1');
Hgraph2D_2 = axes('Units','normalized',...
    'ActivePositionProperty','position',...
    'position',[0.1 0.39 0.85 0.23],...
    'Parent',Panel2D,...
    'tag','graph2D_2');
Hgraph2D_3 = axes('Units','normalized',...
    'ActivePositionProperty','position',...
    'position',[0.1 0.09 0.85 0.23],...
    'Parent',Panel2D,...
    'tag','graph2D_3');

%Creation des boutons
BoutonImportationDeDonnee = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.1 17/20 0.8 2/20],...
    'String','Importation de donnée',...
    'callback',@ImportationDeDonnee);
BoutonLecture = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.1 15/20 0.4 2/20],...
    'String','Lecture',...
    'callback',@Lecture);
BoutonPause = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.5 15/20 0.4 2/20],...
    'String','Pause',...
    'tag','boutonpause',...
    'callback',@PauseReprise);
BoutonVitessePlus = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.3 13/20 0.2 2/20],...
    'String','+',...
    'callback',@VitessePlus);
BoutonVitesseMoin = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.1 13/20 0.2 2/20],...
    'String','-',...
    'callback',@VitesseMoin);
BoutonZoom = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.1 11/20 0.8 2/20],...
    'String','Zoom',...
    'callback',@ZoomMiniMaxi);
BoutonSegSuivant = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.5 7/20 0.4 2/20],...
    'String','suivant',...
    'callback',@SegmentSuivant);
BoutonSegPrecedent = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.1 7/20 0.4 2/20],...
    'String','Precedent',...
    'callback',@SegmentPrecedent);
BoutonSegAvancement = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.5 3/20 0.4 2/20],...
    'String','avancement',...
    'callback',@SegmentAvancement);
BoutonSegRetour = uicontrol('style','pushbutton',...
    'units','normalized',...
    'Parent',PanelMenu,...
    'Position',[0.1 3/20 0.4 2/20],...
    'String','retour',...
    'callback',@SegmentRetour);
IndicSegment = uicontrol('style','text',...
    'units','normalized',...
    'parent',PanelMenu,...
    'position',[0.1 9/20 0.8 1/20],...
    'string','Segment :');

%Creation d'indication
IndicDeplacement = uicontrol('style','edit',...
    'units','normalized',...
    'parent',PanelMenu,...
    'Position',[0.1 1/20 0.8 2/20],...
    'String','Entrer la valeur',...
    'tag','indicdeplacement');
IndicVitesse = uicontrol('style','text',...
    'units','normalized',...
    'parent',PanelMenu,...
    'position',[0.5 13/20 0.5 1.5/20],...
    'string',strcat('vitesse  :  x',num2str(VitesseLecture)));

setappdata(gcf,'indic_vitesse',IndicVitesse);
setappdata(gcf,'vitesse_lecture',VitesseLecture);

setappdata(gcf,'graph3D',Hgraph3D);
setappdata(gcf,'graph2D_1',Hgraph2D_1);
setappdata(gcf,'graph2D_2',Hgraph2D_2);
setappdata(gcf,'graph2D_3',Hgraph2D_3);

setappdata(gcf,'liste_fichier',Liste_Fichier);
setappdata(gcf,'liste_marqueur',Liste_Marqueur);
setappdata(gcf,'tab_temps',Tab_Temps);

setappdata(gcf,'nb_fichier_charger',Nb_Fichier_Charger);
setappdata(gcf,'zoomstatut',ZoomStatut);
setappdata(gcf,'menu_mq',Menu_Mq);
setappdata(gcf,'flag_stop',FlagStop);
setappdata(gcf,'flag_lecture',FlagLecture);